%YAML:1.0
---

EventCam:
  model: 'plumb_bob' #equidistant
  K: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 329.94156,    0.     ,  309.09818,
            0.     ,  329.90821,  236.25427,
            0.     ,    0.     ,    1.     ]
  distortion: !!opencv-matrix
    rows: 5
    cols: 1
    dt: d
    data: [ -0.028820, 0.039504, 0.000046, 0.000361, 0.000000 ]

  height: 480
  width: 640
  DecayFactor: 10.0e-3 # exponential decay factor in ms


IMU:
  ACC_N: 1 # acc noise variance
  ACC_W: 1 # acc bias variance
  GYR_N: 1 # gyr noise variance
  GYR_W: 1 # gyr bias variance
  Gravity: 9.81007


# for ros
event_topic: "/prophesee/left/events"
imu_topic: "/imu/data"
bag_path: "/media/cuili/WantingHDD/zzz/new/sofa_normal1_synced_edited.bag"

# for system
pcd_path: "/home/cuili/zzz/semidense-lines-zzz/results_line_segments/result/new/pc/pc_new_sofa_normal_flow1.pcd"
resultPath: "/home/cuili/zzz/Canny_EVIT/"
start_time: 0 # TBD
dt_event_init: 0.003
dt_event: 0.025
ts_decay_factor: 10.0e-3
ts_decay_factor_init: 10.0e-3

# Extrinsic
Rbc: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1., 0., 0.,
          0., 1., 0.,
          0., 0., 1.]
tbc: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ 0., 0., 0.]


# for optimizer
patchSizeX: 1
patchSizeY: 1
